### ISSUE TITLE
Allow to define extra tags to be used as flags for the php command invocation

### ISSUE THREAD

**Issue by gggeek** [ezsystems/ezplatform-cron#6]
A common use case is f.e. to have `--no-debug` added when running non-prod envs

**Comment by wizhippo** [comment]
Ori in a case like

```
    App\Command\TriggersRunCommand:
        arguments:
            $triggerCollection: '@app.trigger_collection'
        tags:
            - { name: console.command }
            - { name: ezplatform.cron.job, schedule: '0 4 * * *', args: '--group daily' }
            - { name: ezplatform.cron.job, schedule: '0 4 * * 1', args: '--group weekly' }
            - { name: ezplatform.cron.job, schedule: '0 4 1 * *', args: '--group monthly' }
```
